### ISSUE TITLE
Ausência do módulo convertColor

### ISSUE THREAD

**Issue by juniorpires** [lsoaresesilva/corona_view#1]
@lsoaresesilva quando fui rodar o projeto ele dizia não achar o módulo (view.lua:138)  convertcolor.

O convertColor achei nesse outro projeto teu https://github.com/lsoaresesilva/Lua-Color-Converter.

**Comment by lsoaresesilva** [comment]
Corrigi. Faz o clone do projeto novamente que resolve.

**Comment by juniorpires** [comment]
Vou fazer. Valeu Leonardo :D
